# Generated by Django 2.2.2 on 2019-06-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190619_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Author Name', max_length=100, null=True)),
                ('publishID', models.IntegerField(help_text='Author Name', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Book Name', max_length=100, null=True)),
                ('release_date', models.DateField(help_text='Release Date', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(help_text='Genre', max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
