# Generated by Django 2.2.2 on 2019-06-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190620_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.IntegerField(help_text='Enter USN for Student', primary_key=True, serialize=False, verbose_name='USN')),
                ('name', models.CharField(help_text='Student Name', max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('book_author', models.ForeignKey(help_text='Book Author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Author')),
                ('book_name', models.ForeignKey(help_text='Book Name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Book')),
                ('genre', models.ManyToManyField(help_text='genre of book', to='home.Genre')),
            ],
        ),
    ]
