# Generated by Django 2.2.2 on 2019-06-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='book_author',
        ),
        migrations.RemoveField(
            model_name='student',
            name='genre',
        ),
    ]
